export const roles = [
    { value: "all", label: "All Roles" },
    { value: "developer", label: "Developer" },
    { value: "va", label: "Virtual Assistant" },
    { value: "project_manager", label: "Project Manager" },
    { value: "designer", label: "Designer" },
    { value: "ui_ux", label: "UI/UX Designer" },
    { value: "data_analyst", label: "Data Analyst" },
    { value: "content_writer", label: "Content Writer" },
    { value: "marketing", label: "Marketing" },
    { value: "customer_support", label: "Customer Support" },
    { value: "accountant", label: "Accountant" },
    { value: "video_editor", label: "Video Editor" },
    { value: "seo_specialist", label: "SEO Specialist" },
]