import { Code2, Server, Database, LayoutDashboard } from "lucide-react"
import type { Service } from "@/types/service"

export const allServices: Service[] = [
    {
        id: "svc-001",
        icon: Code2,
        number: "01",
        title: "Web Development",
        tagline: "Build modern web apps",
        description: "We provide full-stack web development using the latest technologies.",
        longDescription: "From frontend frameworks to backend APIs, we deliver scalable solutions tailored to your business needs.",
        features: ["Responsive Design", "SEO Optimized", "Cross-browser Compatible"],
        stack: ["React", "Node.js", "TypeScript", "PostgreSQL"],
        category: "Development",
        featured: true,
        badge: "Popular",
        active: true,
        inquiries: 25,
    },
    {
        id: "svc-002",
        icon: Server,
        number: "02",
        title: "Outsourced IT Support",
        tagline: "Reliable IT operations",
        description: "Managed IT services for businesses, including monitoring, support, and troubleshooting.",
        features: ["24/7 Monitoring", "Helpdesk Support", "Network Management"],
        stack: ["Linux", "Windows Server", "Docker", "AWS"],
        category: "Outsourcing",
        active: true,
        inquiries: 12,
    },
    {
        id: "svc-003",
        icon: Database,
        number: "03",
        title: "Database Management",
        tagline: "Secure & optimized data",
        description: "Design, optimize, and maintain your database systems for high performance.",
        features: ["Backups & Recovery", "Data Security", "Performance Tuning"],
        stack: ["PostgreSQL", "MongoDB", "MySQL", "Redis"],
        category: "Development",
        featured: false,
        active: true,
        inquiries: 7,
    },
    {
        id: "svc-004",
        icon: LayoutDashboard,
        number: "04",
        title: "UI/UX Design",
        tagline: "Engaging interfaces",
        description: "We create user-friendly designs that improve usability and engagement.",
        features: ["Wireframing", "Prototyping", "User Testing"],
        stack: ["Figma", "Sketch", "Adobe XD"],
        category: "Development",
        active: true,
        inquiries: 18,
    },
]