import {
  BarChart2,
  Blocks,
  Code2,
  Cpu,
  Globe,
  Headphones, PenTool,
  Shield,
  Smartphone,
  TrendingUp,
  Users,
  Video,
  type LucideIcon
} from "lucide-react"

type Service = {
  id: string
  icon: LucideIcon
  number: string
  title: string
  tagline: string
  description: string
  longDescription?: string
  features: string[]
  stack: string[]
  category: "Development" | "Outsourcing"
  featured?: boolean
  badge?: string
  active: boolean
  inquiries: number
}

export const allServices: Service[] = [
  {
    id: "frontend",
    icon: Code2,
    number: "01",
    category: "Development",
    title: "Frontend Development",
    tagline: "Interfaces that users love to use.",
    description: "We build fast, accessible, and beautiful frontend experiences using modern frameworks.",
    longDescription:
      "Our frontend developers specialize in creating pixel-perfect, performant user interfaces. From simple landing pages to complex single-page applications, we ensure your users get a seamless experience across all devices and browsers. We follow best practices for accessibility, SEO, and performance out of the box.",
    features: [
      "React, Next.js, Vue & Angular specialists",
      "Responsive and mobile-first design",
      "Performance optimization & Core Web Vitals",
      "UI component libraries & design systems",
      "SEO-friendly and accessible markup",
    ],
    stack: ["React", "Next.js", "Vue", "TypeScript", "Tailwind CSS", "Figma", "Storybook", "Vercel"],
    active: true,
    inquiries: 402,
  },
  {
    id: "mobile",
    icon: Smartphone,
    number: "02",
    category: "Development",
    title: "Mobile Development",
    tagline: "Apps built for every screen.",
    description: "From native iOS and Android to cross-platform solutions, our mobile developers create high-performance apps.",
    longDescription:
      "We build mobile apps that feel native and perform flawlessly. Whether you need a cross-platform app using React Native or Flutter, or a fully native iOS/Android experience, our developers deliver apps that users love. We handle everything from design to App Store submission.",
    features: [
      "iOS (Swift, SwiftUI) & Android (Kotlin) native",
      "React Native & Flutter cross-platform",
      "App Store & Google Play deployment",
      "Push notifications & offline capabilities",
      "API integration & backend connectivity",
    ],
    stack: ["React Native", "Flutter", "Swift", "Kotlin", "Expo", "Firebase", "Supabase", "Xcode"],
    active: true,
    inquiries: 72,
  },
  {
    id: "web",
    icon: Globe,
    number: "03",
    category: "Development",
    title: "Web Development",
    tagline: "Full-stack solutions, end to end.",
    description: "Our full-stack developers handle everything from database design and API architecture to frontend delivery.",
    longDescription:
      "We build complete web applications from the ground up. Our full-stack developers are proficient in both frontend and backend technologies, allowing us to deliver cohesive, scalable solutions. From architecting databases to deploying on cloud infrastructure, we own the entire process.",
    features: [
      "Full-stack web application development",
      "REST & GraphQL API design and development",
      "Database architecture & optimization",
      "Cloud deployment & CI/CD pipelines",
      "Authentication, security & performance",
    ],
    stack: ["Node.js", "Python", "PostgreSQL", "MySQL", "Docker", "AWS", "Redis", "Nginx"],
    active: true,
    inquiries: 3423,
  },
  {
    id: "blockchain",
    icon: Blocks,
    number: "04",
    category: "Development",
    title: "Blockchain & Web3",
    tagline: "Decentralized. Secure. Future-ready.",
    description: "Led by a certified Web3 developer, we build blockchain solutions that are secure, audited, and production-ready.",
    longDescription:
      "We are one of the few Philippine-based teams with a certified Web3 developer leading blockchain projects. From writing and auditing smart contracts to building full DeFi protocols and NFT platforms, we bring deep technical expertise to every project. All smart contracts undergo thorough security review before deployment.",
    features: [
      "Smart contract development & auditing (Solidity)",
      "DeFi protocol design & implementation",
      "NFT marketplace & minting platforms",
      "DAO governance & token economics",
      "Web3 wallet integration (MetaMask, WalletConnect)",
    ],
    stack: ["Solidity", "Ethereum", "Polygon", "Hardhat", "Web3.js", "Ethers.js", "IPFS", "OpenZeppelin"],
    featured: true,
    badge: "Certified Web3 Developer",
    active: true,
    inquiries: 20,
  },
  {
    id: "ai",
    icon: Cpu,
    number: "05",
    category: "Development",
    title: "AI & Automation",
    tagline: "Work smarter. Scale faster.",
    description: "We integrate AI into your workflows and build automation solutions that eliminate repetitive tasks.",
    longDescription:
      "AI is no longer optional — it's a competitive advantage. We help businesses integrate large language models, build intelligent agents, and automate repetitive workflows. Whether you need a custom chatbot, a data pipeline, or a full ML model, we make AI work for your specific business context.",
    features: [
      "LLM integration (OpenAI, Claude, Gemini)",
      "Custom AI chatbots & agents",
      "Workflow automation & RPA",
      "Data pipelines & ETL processes",
      "Predictive analytics & ML models",
    ],
    stack: ["Python", "OpenAI", "LangChain", "TensorFlow", "n8n", "Zapier", "Pandas", "FastAPI"],
    active: true,
    inquiries: 42,
  },
  {
    id: "security",
    icon: Shield,
    number: "06",
    category: "Development",
    title: "Cybersecurity",
    tagline: "Protect what you have built.",
    description: "Our security specialists help you identify vulnerabilities, harden your systems, and build security-first practices.",
    longDescription:
      "Security is not an afterthought — it is foundational. Our cybersecurity specialists conduct thorough penetration tests, security audits, and code reviews to identify and fix vulnerabilities before they become breaches. We also help teams adopt DevSecOps practices for long-term security.",
    features: [
      "Penetration testing & vulnerability assessments",
      "Security code review & audits",
      "DevSecOps implementation",
      "OWASP compliance & hardening",
      "Incident response & recovery planning",
    ],
    stack: ["Burp Suite", "Metasploit", "Nessus", "OWASP", "Snyk", "SonarQube", "Kali Linux", "Vault"],
    active: true,
    inquiries: 5063,
  },
  {
    id: "va",
    icon: Users,
    number: "07",
    category: "Outsourcing",
    title: "Virtual Assistants",
    tagline: "Delegate more. Achieve more.",
    description: "Our VAs are proactive partners who keep operations running smoothly so you can focus on growth.",
    longDescription:
      "Our virtual assistants are not just task handlers — they are proactive business partners. Trained in modern productivity tools and business communication, our VAs adapt to your workflow quickly and take ownership of their responsibilities. From inbox zero to complex research projects, they have you covered.",
    features: [
      "Executive & administrative support",
      "Calendar & inbox management",
      "Data entry, research & reporting",
      "Social media & content scheduling",
      "Customer coordination & follow-ups",
    ],
    stack: ["Notion", "Slack", "HubSpot", "Zoho", "Trello", "Asana", "Gmail", "Shopify"],
    active: true,
    inquiries: 124,
  },
  {
    id: "data",
    icon: BarChart2,
    number: "08",
    category: "Outsourcing",
    title: "Data Analysts",
    tagline: "Turn data into decisions.",
    description: "Our data analysts build dashboards, reports, and models that drive better business decisions.",
    longDescription:
      "Raw data is worthless without interpretation. Our data analysts help you collect, clean, and visualize your business data in ways that reveal actionable insights. From building automated reporting dashboards to building predictive models, we turn your numbers into a competitive advantage.",
    features: [
      "Business intelligence & dashboard development",
      "Data cleaning, transformation & pipelines",
      "KPI definition & performance reporting",
      "SQL query optimization & data modeling",
      "Google Analytics, Mixpanel & product analytics",
    ],
    stack: ["Python", "SQL", "Power BI", "Tableau", "Looker", "BigQuery", "Excel", "dbt"],
    active: true,
    inquiries: 187,
  },
  {
    id: "support",
    icon: Headphones,
    number: "09",
    category: "Outsourcing",
    title: "Customer Support",
    tagline: "Every customer, every channel.",
    description: "Professional support agents who represent your brand with care across all channels.",
    longDescription:
      "Your customers deserve fast, friendly, and knowledgeable support. Our customer support agents are trained in your product and brand voice before their first interaction. We cover live chat, email, phone, and social media — with full quality monitoring and CSAT tracking included.",
    features: [
      "Live chat & email support",
      "Phone & voice support",
      "Ticket management & escalation handling",
      "Onboarding assistance & product guidance",
      "CSAT tracking & quality monitoring",
    ],
    stack: ["Zendesk", "Intercom", "Freshdesk", "HubSpot", "Gorgias", "Slack", "Notion", "Loom"],
    active: true,
    inquiries: 152,
  },
  {
    id: "design",
    icon: PenTool,
    number: "10",
    category: "Outsourcing",
    title: "UI/UX Designers",
    tagline: "Design that converts.",
    description: "Our designers craft intuitive, beautiful experiences backed by research and tested with real users.",
    longDescription:
      "Good design is not just about aesthetics — it's about outcomes. Our UI/UX designers combine user research, interaction design, and visual design to create experiences that convert visitors into customers. Every design decision is backed by data and validated with real users.",
    features: [
      "User research & persona development",
      "Wireframing & interactive prototyping",
      "UI design & design system creation",
      "Usability testing & iteration",
      "Handoff-ready Figma files for developers",
    ],
    stack: ["Figma", "Adobe XD", "Framer", "Zeplin", "Maze", "Hotjar", "Miro", "Notion"],
    active: true,
    inquiries: 142,
  },
  {
    id: "marketing",
    icon: TrendingUp,
    number: "11",
    category: "Outsourcing",
    title: "Marketing & SEO",
    tagline: "Grow your reach. Own your niche.",
    description: "Our marketing specialists drive organic and paid growth across all channels.",
    longDescription:
      "Visibility is everything in a competitive market. Our marketing specialists help you rank higher, reach more people, and convert better. From technical SEO audits to full-funnel paid campaigns, we cover every channel that matters for your business growth.",
    features: [
      "SEO audits, strategy & on-page optimization",
      "Content marketing & blog writing",
      "Social media management & growth",
      "Email marketing & automation",
      "Google Ads & Meta Ads management",
    ],
    stack: ["SEMrush", "Ahrefs", "Google Analytics", "Mailchimp", "Meta Ads", "WordPress", "Webflow", "Canva"],
    active: true,
    inquiries: 43,
  },
  {
    id: "video",
    icon: Video,
    number: "12",
    category: "Outsourcing",
    title: "Video Editors",
    tagline: "Content that stops the scroll.",
    description: "Professional editors who turn raw footage into polished, branded content for any platform.",
    longDescription:
      "Video is the most powerful content format today — and it needs to be done right. Our video editors are skilled in storytelling, pacing, and brand consistency. Whether you need long-form YouTube content, short-form social videos, or branded corporate content, we deliver on time and on brand.",
    features: [
      "YouTube & long-form video editing",
      "Short-form content (Reels, TikTok, Shorts)",
      "Motion graphics & animated text",
      "Color grading & audio mixing",
      "Brand kit integration & consistency",
    ],
    stack: ["Premiere Pro", "After Effects", "DaVinci Resolve", "CapCut", "Final Cut Pro", "Canva", "Figma", "Audition"],
    active: true,
    inquiries: 14,
  },
]

export const developmentServices: Service[] = [
  {
    id: "frontend",
    icon: Code2,
    number: "01",
    category: "Development",
    title: "Frontend Development",
    tagline: "Interfaces that users love to use.",
    description: "We build fast, accessible, and beautiful frontend experiences using modern frameworks.",
    longDescription:
      "Our frontend developers specialize in creating pixel-perfect, performant user interfaces. From simple landing pages to complex single-page applications, we ensure your users get a seamless experience across all devices and browsers. We follow best practices for accessibility, SEO, and performance out of the box.",
    features: [
      "React, Next.js, Vue & Angular specialists",
      "Responsive and mobile-first design",
      "Performance optimization & Core Web Vitals",
      "UI component libraries & design systems",
      "SEO-friendly and accessible markup",
    ],
    stack: ["React", "Next.js", "Vue", "TypeScript", "Tailwind CSS", "Figma", "Storybook", "Vercel"],
    active: true,
    inquiries: 402,
  },
  {
    id: "mobile",
    icon: Smartphone,
    number: "02",
    category: "Development",
    title: "Mobile Development",
    tagline: "Apps built for every screen.",
    description: "From native iOS and Android to cross-platform solutions, our mobile developers create high-performance apps.",
    longDescription:
      "We build mobile apps that feel native and perform flawlessly. Whether you need a cross-platform app using React Native or Flutter, or a fully native iOS/Android experience, our developers deliver apps that users love. We handle everything from design to App Store submission.",
    features: [
      "iOS (Swift, SwiftUI) & Android (Kotlin) native",
      "React Native & Flutter cross-platform",
      "App Store & Google Play deployment",
      "Push notifications & offline capabilities",
      "API integration & backend connectivity",
    ],
    stack: ["React Native", "Flutter", "Swift", "Kotlin", "Expo", "Firebase", "Supabase", "Xcode"],
    active: true,
    inquiries: 72,
  },
  {
    id: "web",
    icon: Globe,
    number: "03",
    category: "Development",
    title: "Web Development",
    tagline: "Full-stack solutions, end to end.",
    description: "Our full-stack developers handle everything from database design and API architecture to frontend delivery.",
    longDescription:
      "We build complete web applications from the ground up. Our full-stack developers are proficient in both frontend and backend technologies, allowing us to deliver cohesive, scalable solutions. From architecting databases to deploying on cloud infrastructure, we own the entire process.",
    features: [
      "Full-stack web application development",
      "REST & GraphQL API design and development",
      "Database architecture & optimization",
      "Cloud deployment & CI/CD pipelines",
      "Authentication, security & performance",
    ],
    stack: ["Node.js", "Python", "PostgreSQL", "MySQL", "Docker", "AWS", "Redis", "Nginx"],
    active: true,
    inquiries: 3423,
  },
  {
    id: "blockchain",
    icon: Blocks,
    number: "04",
    category: "Development",
    title: "Blockchain & Web3",
    tagline: "Decentralized. Secure. Future-ready.",
    description: "Led by a certified Web3 developer, we build blockchain solutions that are secure, audited, and production-ready.",
    longDescription:
      "We are one of the few Philippine-based teams with a certified Web3 developer leading blockchain projects. From writing and auditing smart contracts to building full DeFi protocols and NFT platforms, we bring deep technical expertise to every project. All smart contracts undergo thorough security review before deployment.",
    features: [
      "Smart contract development & auditing (Solidity)",
      "DeFi protocol design & implementation",
      "NFT marketplace & minting platforms",
      "DAO governance & token economics",
      "Web3 wallet integration (MetaMask, WalletConnect)",
    ],
    stack: ["Solidity", "Ethereum", "Polygon", "Hardhat", "Web3.js", "Ethers.js", "IPFS", "OpenZeppelin"],
    featured: true,
    badge: "Certified Web3 Developer",
    active: true,
    inquiries: 20,
  },
  {
    id: "ai",
    icon: Cpu,
    number: "05",
    category: "Development",
    title: "AI & Automation",
    tagline: "Work smarter. Scale faster.",
    description: "We integrate AI into your workflows and build automation solutions that eliminate repetitive tasks.",
    longDescription:
      "AI is no longer optional — it's a competitive advantage. We help businesses integrate large language models, build intelligent agents, and automate repetitive workflows. Whether you need a custom chatbot, a data pipeline, or a full ML model, we make AI work for your specific business context.",
    features: [
      "LLM integration (OpenAI, Claude, Gemini)",
      "Custom AI chatbots & agents",
      "Workflow automation & RPA",
      "Data pipelines & ETL processes",
      "Predictive analytics & ML models",
    ],
    stack: ["Python", "OpenAI", "LangChain", "TensorFlow", "n8n", "Zapier", "Pandas", "FastAPI"],
    active: true,
    inquiries: 42,
  },
  {
    id: "security",
    icon: Shield,
    number: "06",
    category: "Development",
    title: "Cybersecurity",
    tagline: "Protect what you have built.",
    description: "Our security specialists help you identify vulnerabilities, harden your systems, and build security-first practices.",
    longDescription:
      "Security is not an afterthought — it is foundational. Our cybersecurity specialists conduct thorough penetration tests, security audits, and code reviews to identify and fix vulnerabilities before they become breaches. We also help teams adopt DevSecOps practices for long-term security.",
    features: [
      "Penetration testing & vulnerability assessments",
      "Security code review & audits",
      "DevSecOps implementation",
      "OWASP compliance & hardening",
      "Incident response & recovery planning",
    ],
    stack: ["Burp Suite", "Metasploit", "Nessus", "OWASP", "Snyk", "SonarQube", "Kali Linux", "Vault"],
    active: true,
    inquiries: 5063,
  },
]

export const outsourcingServices: Service[] = [
  {
    id: "va",
    icon: Users,
    number: "07",
    category: "Outsourcing",
    title: "Virtual Assistants",
    tagline: "Delegate more. Achieve more.",
    description: "Our VAs are proactive partners who keep operations running smoothly so you can focus on growth.",
    longDescription:
      "Our virtual assistants are not just task handlers — they are proactive business partners. Trained in modern productivity tools and business communication, our VAs adapt to your workflow quickly and take ownership of their responsibilities. From inbox zero to complex research projects, they have you covered.",
    features: [
      "Executive & administrative support",
      "Calendar & inbox management",
      "Data entry, research & reporting",
      "Social media & content scheduling",
      "Customer coordination & follow-ups",
    ],
    stack: ["Notion", "Slack", "HubSpot", "Zoho", "Trello", "Asana", "Gmail", "Shopify"],
    active: true,
    inquiries: 124,
  },
  {
    id: "data",
    icon: BarChart2,
    number: "08",
    category: "Outsourcing",
    title: "Data Analysts",
    tagline: "Turn data into decisions.",
    description: "Our data analysts build dashboards, reports, and models that drive better business decisions.",
    longDescription:
      "Raw data is worthless without interpretation. Our data analysts help you collect, clean, and visualize your business data in ways that reveal actionable insights. From building automated reporting dashboards to building predictive models, we turn your numbers into a competitive advantage.",
    features: [
      "Business intelligence & dashboard development",
      "Data cleaning, transformation & pipelines",
      "KPI definition & performance reporting",
      "SQL query optimization & data modeling",
      "Google Analytics, Mixpanel & product analytics",
    ],
    stack: ["Python", "SQL", "Power BI", "Tableau", "Looker", "BigQuery", "Excel", "dbt"],
    active: true,
    inquiries: 187,
  },
  {
    id: "support",
    icon: Headphones,
    number: "09",
    category: "Outsourcing",
    title: "Customer Support",
    tagline: "Every customer, every channel.",
    description: "Professional support agents who represent your brand with care across all channels.",
    longDescription:
      "Your customers deserve fast, friendly, and knowledgeable support. Our customer support agents are trained in your product and brand voice before their first interaction. We cover live chat, email, phone, and social media — with full quality monitoring and CSAT tracking included.",
    features: [
      "Live chat & email support",
      "Phone & voice support",
      "Ticket management & escalation handling",
      "Onboarding assistance & product guidance",
      "CSAT tracking & quality monitoring",
    ],
    stack: ["Zendesk", "Intercom", "Freshdesk", "HubSpot", "Gorgias", "Slack", "Notion", "Loom"],
    active: true,
    inquiries: 152,
  },
  {
    id: "design",
    icon: PenTool,
    number: "10",
    category: "Outsourcing",
    title: "UI/UX Designers",
    tagline: "Design that converts.",
    description: "Our designers craft intuitive, beautiful experiences backed by research and tested with real users.",
    longDescription:
      "Good design is not just about aesthetics — it's about outcomes. Our UI/UX designers combine user research, interaction design, and visual design to create experiences that convert visitors into customers. Every design decision is backed by data and validated with real users.",
    features: [
      "User research & persona development",
      "Wireframing & interactive prototyping",
      "UI design & design system creation",
      "Usability testing & iteration",
      "Handoff-ready Figma files for developers",
    ],
    stack: ["Figma", "Adobe XD", "Framer", "Zeplin", "Maze", "Hotjar", "Miro", "Notion"],
    active: true,
    inquiries: 142,
  },
  {
    id: "marketing",
    icon: TrendingUp,
    number: "11",
    category: "Outsourcing",
    title: "Marketing & SEO",
    tagline: "Grow your reach. Own your niche.",
    description: "Our marketing specialists drive organic and paid growth across all channels.",
    longDescription:
      "Visibility is everything in a competitive market. Our marketing specialists help you rank higher, reach more people, and convert better. From technical SEO audits to full-funnel paid campaigns, we cover every channel that matters for your business growth.",
    features: [
      "SEO audits, strategy & on-page optimization",
      "Content marketing & blog writing",
      "Social media management & growth",
      "Email marketing & automation",
      "Google Ads & Meta Ads management",
    ],
    stack: ["SEMrush", "Ahrefs", "Google Analytics", "Mailchimp", "Meta Ads", "WordPress", "Webflow", "Canva"],
    active: true,
    inquiries: 43,
  },
  {
    id: "video",
    icon: Video,
    number: "12",
    category: "Outsourcing",
    title: "Video Editors",
    tagline: "Content that stops the scroll.",
    description: "Professional editors who turn raw footage into polished, branded content for any platform.",
    longDescription:
      "Video is the most powerful content format today — and it needs to be done right. Our video editors are skilled in storytelling, pacing, and brand consistency. Whether you need long-form YouTube content, short-form social videos, or branded corporate content, we deliver on time and on brand.",
    features: [
      "YouTube & long-form video editing",
      "Short-form content (Reels, TikTok, Shorts)",
      "Motion graphics & animated text",
      "Color grading & audio mixing",
      "Brand kit integration & consistency",
    ],
    stack: ["Premiere Pro", "After Effects", "DaVinci Resolve", "CapCut", "Final Cut Pro", "Canva", "Figma", "Audition"],
    active: true,
    inquiries: 14,
  },
]

export const process = [
  {
    step: "01",
    title: "Tell Us What You Need",
    description: "Share your requirements, timeline, and budget. We'll identify the right talent profile for your goals.",
  },
  {
    step: "02",
    title: "We Match You",
    description: "Within 48 hours, we present you with pre-vetted candidates that fit your exact requirements.",
  },
  {
    step: "03",
    title: "Interview & Choose",
    description: "Meet the candidates, ask your questions, and choose the one you're most confident in.",
  },
  {
    step: "04",
    title: "Start Working",
    description: "Onboard your new team member and hit the ground running. We stay available for ongoing support.",
  },
]