import { Talent } from "@/types";

export const talents: Talent[] = [

    // ── Developers ────────────────────────────────────────────
    {
        id: "1",
        name: "Alex Rivera",
        email: "alex.rivera@example.com",
        role: "developer",
        title: "Full-Stack Developer",
        hourlyRate: "45.00",
        skills: ["React", "Node.js", "PostgreSQL", "TypeScript"],
        status: "available",
        rating: "4.9",
        projectsCompleted: 42,
        bio: "8 years building scalable web applications for startups and enterprises. Specialist in React ecosystems and cloud-native architecture.",
        gradient: "from-blue-500 to-cyan-400",
        avatarUrl: null,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "4",
        name: "Priya Mehta",
        email: "priya.mehta@example.com",
        role: "developer",
        title: "Frontend Developer",
        hourlyRate: "40.00",
        skills: ["Next.js", "Tailwind", "TypeScript", "Figma"],
        status: "available",
        rating: "4.9",
        projectsCompleted: 56,
        bio: "Pixel-perfect frontend developer who bridges design and engineering. Passionate about performance, accessibility, and great UX.",
        gradient: "from-emerald-500 to-teal-400",
        avatarUrl: null,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "5",
        name: "Carlos Mendez",
        email: "carlos.mendez@example.com",
        role: "developer",
        title: "Backend Developer",
        hourlyRate: "50.00",
        skills: ["Python", "Django", "AWS", "Docker"],
        status: "available",
        rating: "4.7",
        projectsCompleted: 38,
        bio: "Backend specialist focused on building robust APIs and cloud infrastructure. Experienced with high-traffic systems and microservices.",
        gradient: "from-orange-500 to-amber-400",
        avatarUrl: null,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "9",
        name: "Liam Torres",
        email: "liam.torres@example.com",
        role: "developer",
        title: "Blockchain Developer",
        hourlyRate: "75.00",
        skills: ["Solidity", "Ethereum", "Web3.js", "Hardhat"],
        status: "available",
        rating: "4.9",
        projectsCompleted: 19,
        bio: "Smart contract engineer with deep expertise in DeFi protocols and NFT platforms. Audited 10+ production contracts with zero critical vulnerabilities.",
        gradient: "from-indigo-500 to-violet-400",
        avatarUrl: null,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "10",
        name: "Yuna Park",
        email: "yuna.park@example.com",
        role: "developer",
        title: "DevOps Engineer",
        hourlyRate: "65.00",
        skills: ["Kubernetes", "Terraform", "CI/CD", "GCP"],
        status: "available",
        rating: "4.8",
        projectsCompleted: 33,
        bio: "Infrastructure engineer who lives in the terminal. Specializes in zero-downtime deployments, cost optimization, and building DevOps culture from scratch.",
        gradient: "from-cyan-500 to-sky-400",
        avatarUrl: null,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "11",
        name: "Marco Reyes",
        email: "marco.reyes@example.com",
        role: "developer",
        title: "AI / ML Engineer",
        hourlyRate: "80.00",
        skills: ["Python", "PyTorch", "LangChain", "OpenAI API"],
        status: "available",
        rating: "5.0",
        projectsCompleted: 17,
        bio: "Machine learning engineer focused on LLM integration and production AI pipelines. Built RAG systems and fine-tuned models for 3 SaaS products.",
        gradient: "from-amber-500 to-orange-400",
        avatarUrl: null,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "8",
        name: "Aisha Patel",
        email: "aisha.patel@example.com",
        role: "developer",
        title: "Mobile Developer",
        hourlyRate: "48.00",
        skills: ["React Native", "iOS", "Android", "Expo"],
        status: "busy",
        rating: "4.8",
        projectsCompleted: 29,
        bio: "Mobile-first developer with 6 years shipping apps on both iOS and Android. Expert in React Native and cross-platform performance.",
        gradient: "from-lime-500 to-green-400",
        avatarUrl: null,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },

    // ── Virtual Assistants ────────────────────────────────────
    {
        id: "2",
        name: "Maria Santos",
        email: "maria.santos@example.com",
        role: "va",
        title: "Virtual Assistant",
        hourlyRate: "20.00",
        skills: ["Admin", "CRM", "Support", "Scheduling"],
        status: "unavailable",
        rating: "5.0",
        projectsCompleted: 78,
        bio: "Detail-oriented VA with 5 years of executive support experience. Expert in automating workflows and managing high-volume inboxes.",
        gradient: "from-rose-500 to-pink-400",
        avatarUrl: null,
        isVisible: false,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "6",
        name: "Sophie Chen",
        email: "sophie.chen@example.com",
        role: "va",
        title: "Executive Assistant",
        hourlyRate: "25.00",
        skills: ["Notion", "Slack", "Research", "Social Media"],
        status: "available",
        rating: "4.9",
        projectsCompleted: 63,
        bio: "Proactive EA with a background in operations. Highly organized, discreet, and experienced working with C-suite executives.",
        gradient: "from-fuchsia-500 to-pink-400",
        avatarUrl: null,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "12",
        name: "Fatima Reyes",
        email: "fatima.reyes@example.com",
        role: "va",
        title: "E-commerce VA",
        hourlyRate: "22.00",
        skills: ["Shopify", "Amazon FBA", "Canva", "Customer Support"],
        status: "available",
        rating: "4.9",
        projectsCompleted: 51,
        bio: "E-commerce specialist managing product listings, order fulfillment, and customer service for 7-figure Shopify and Amazon stores.",
        gradient: "from-rose-500 to-red-400",
        avatarUrl: null,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "13",
        name: "Grace Villanueva",
        email: "grace.villanueva@example.com",
        role: "va",
        title: "Social Media Manager",
        hourlyRate: "28.00",
        skills: ["Instagram", "LinkedIn", "Content Planning", "Analytics"],
        status: "available",
        rating: "4.8",
        projectsCompleted: 44,
        bio: "Social media strategist who turns brand voices into engaged communities. Managed accounts growing from 0 to 50K followers across multiple industries.",
        gradient: "from-pink-500 to-fuchsia-400",
        avatarUrl: null,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },

    // ── Project Managers ──────────────────────────────────────
    {
        id: "3",
        name: "James Kwon",
        email: "james.kwon@example.com",
        role: "project_manager",
        title: "Project Manager",
        hourlyRate: "55.00",
        skills: ["Agile", "Scrum", "Jira", "Risk Management"],
        status: "busy",
        rating: "4.8",
        projectsCompleted: 31,
        bio: "PMP-certified PM with a track record of delivering complex projects on time. Experienced in managing distributed teams across time zones.",
        gradient: "from-violet-500 to-purple-400",
        avatarUrl: null,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "7",
        name: "Daniel Osei",
        email: "daniel.osei@example.com",
        role: "project_manager",
        title: "Scrum Master",
        hourlyRate: "60.00",
        skills: ["Scrum", "Kanban", "Confluence", "Leadership"],
        status: "available",
        rating: "5.0",
        projectsCompleted: 24,
        bio: "Certified Scrum Master who coaches teams to peak performance. Focused on removing blockers and building high-trust team cultures.",
        gradient: "from-sky-500 to-blue-400",
        avatarUrl: null,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "14",
        name: "Nathan Cruz",
        email: "nathan.cruz@example.com",
        role: "project_manager",
        title: "Technical Program Manager",
        hourlyRate: "70.00",
        skills: ["Roadmapping", "Stakeholder Management", "OKRs", "Linear"],
        status: "busy",
        rating: "4.9",
        projectsCompleted: 22,
        bio: "TPM with an engineering background who bridges product and engineering seamlessly. Experienced running programs across 4 time zones with 30+ person teams.",
        gradient: "from-violet-500 to-indigo-400",
        avatarUrl: null,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },

    // ── Designers ─────────────────────────────────────────────
    {
        id: "15",
        name: "Camille Fontaine",
        email: "camille.fontaine@example.com",
        role: "designer",
        title: "Graphic Designer",
        hourlyRate: "45.00",
        skills: ["Photoshop", "Illustrator", "InDesign", "Branding"],
        status: "available",
        rating: "5.0",
        projectsCompleted: 47,
        bio: "Versatile graphic designer with 8 years of experience in print and digital. Has shaped the visual identity of 20+ brands across various industries.",
        gradient: "from-fuchsia-500 to-rose-400",
        avatarUrl: null,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "16",
        name: "Rafael Domingo",
        email: "rafael.domingo@example.com",
        role: "designer",
        title: "Brand & Motion Designer",
        hourlyRate: "50.00",
        skills: ["After Effects", "Illustrator", "Lottie", "Branding"],
        status: "available",
        rating: "4.8",
        projectsCompleted: 38,
        bio: "Visual storyteller specializing in brand identity and motion graphics. Has shaped the visual identity of 20+ companies from seed to Series B.",
        gradient: "from-orange-500 to-yellow-400",
        avatarUrl: null,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },

    // ── UI/UX Designers ───────────────────────────────────────
    {
        id: "21",
        name: "Hana Kimura",
        email: "hana.kimura@example.com",
        role: "ui_ux",
        title: "UI/UX Designer",
        hourlyRate: "55.00",
        skills: ["Figma", "User Research", "Prototyping", "Design Systems"],
        status: "available",
        rating: "5.0",
        projectsCompleted: 41,
        bio: "Product designer with a background in cognitive psychology. Creates interfaces that feel intuitive on first use — without a tutorial in sight.",
        gradient: "from-violet-500 to-fuchsia-400",
        avatarUrl: null,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "22",
        name: "Diego Morales",
        email: "diego.morales@example.com",
        role: "ui_ux",
        title: "Product Designer",
        hourlyRate: "58.00",
        skills: ["Figma", "Framer", "Usability Testing", "Wireframing"],
        status: "busy",
        rating: "4.8",
        projectsCompleted: 34,
        bio: "End-to-end product designer who owns projects from user research through pixel-perfect handoff. Deeply empathetic and data-informed in every design decision.",
        gradient: "from-blue-500 to-violet-400",
        avatarUrl: null,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },

    // ── Data Analysts ─────────────────────────────────────────
    {
        id: "23",
        name: "Selin Aydın",
        email: "selin.aydin@example.com",
        role: "data_analyst",
        title: "Data Analyst",
        hourlyRate: "52.00",
        skills: ["Python", "SQL", "Tableau", "Power BI"],
        status: "available",
        rating: "4.9",
        projectsCompleted: 28,
        bio: "Analytical thinker who transforms raw data into clear business insights. Built dashboards tracking $50M+ in revenue across 3 enterprise clients.",
        gradient: "from-teal-500 to-cyan-400",
        avatarUrl: null,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "24",
        name: "Omar Farouk",
        email: "omar.farouk@example.com",
        role: "data_analyst",
        title: "Business Intelligence Analyst",
        hourlyRate: "58.00",
        skills: ["dbt", "Looker", "BigQuery", "Excel"],
        status: "available",
        rating: "4.7",
        projectsCompleted: 22,
        bio: "BI specialist who builds the data infrastructure that lets teams make faster decisions. Experienced in e-commerce, fintech, and SaaS verticals.",
        gradient: "from-amber-500 to-yellow-400",
        avatarUrl: null,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },

    // ── Content Writers ───────────────────────────────────────
    {
        id: "25",
        name: "Isla MacPherson",
        email: "isla.macpherson@example.com",
        role: "content_writer",
        title: "Content Writer",
        hourlyRate: "35.00",
        skills: ["Copywriting", "SEO Writing", "Blog Posts", "Email Campaigns"],
        status: "available",
        rating: "4.9",
        projectsCompleted: 89,
        bio: "Versatile writer who crafts content that ranks and converts. Produced 500+ articles across SaaS, health, and finance niches over 6 years.",
        gradient: "from-lime-500 to-emerald-400",
        avatarUrl: null,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "26",
        name: "Tomás Herrera",
        email: "tomas.herrera@example.com",
        role: "content_writer",
        title: "Technical Writer",
        hourlyRate: "40.00",
        skills: ["API Docs", "Developer Guides", "Markdown", "Confluence"],
        status: "available",
        rating: "4.8",
        projectsCompleted: 53,
        bio: "Technical writer who makes complex systems understandable. Documented 15+ APIs and built doc sites that reduced support tickets by 40%.",
        gradient: "from-sky-500 to-blue-400",
        avatarUrl: null,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },

    // ── Marketing ─────────────────────────────────────────────
    {
        id: "27",
        name: "Zoe Andersen",
        email: "zoe.andersen@example.com",
        role: "marketing",
        title: "Digital Marketing Strategist",
        hourlyRate: "55.00",
        skills: ["Google Ads", "Meta Ads", "HubSpot", "Growth Hacking"],
        status: "available",
        rating: "4.9",
        projectsCompleted: 36,
        bio: "Performance marketer obsessed with ROAS and LTV. Managed $2M+ in ad spend and built growth engines for B2B SaaS companies.",
        gradient: "from-rose-500 to-orange-400",
        avatarUrl: null,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "28",
        name: "Jin-ho Bae",
        email: "jinho.bae@example.com",
        role: "marketing",
        title: "Email Marketing Specialist",
        hourlyRate: "42.00",
        skills: ["Klaviyo", "Mailchimp", "A/B Testing", "Segmentation"],
        status: "busy",
        rating: "4.7",
        projectsCompleted: 44,
        bio: "Email specialist who turns lists into revenue. Achieved consistent 35%+ open rates and built automated flows generating 6-figures in monthly recurring revenue.",
        gradient: "from-fuchsia-500 to-violet-400",
        avatarUrl: null,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },

    // ── Customer Support ──────────────────────────────────────
    {
        id: "29",
        name: "Amara Diallo",
        email: "amara.diallo@example.com",
        role: "customer_support",
        title: "Customer Support Specialist",
        hourlyRate: "22.00",
        skills: ["Zendesk", "Intercom", "Live Chat", "CRM"],
        status: "available",
        rating: "5.0",
        projectsCompleted: 112,
        bio: "Empathetic support specialist with a 98% CSAT score across 5 years. Specializes in turning frustrated customers into loyal brand advocates.",
        gradient: "from-green-500 to-teal-400",
        avatarUrl: null,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "30",
        name: "Riku Tanaka",
        email: "riku.tanaka@example.com",
        role: "customer_support",
        title: "Support Team Lead",
        hourlyRate: "32.00",
        skills: ["Team Leadership", "Escalation Management", "Freshdesk", "SLA"],
        status: "available",
        rating: "4.8",
        projectsCompleted: 67,
        bio: "Support lead who builds and mentors high-performing teams. Reduced average resolution time by 45% at his last two companies through process redesign.",
        gradient: "from-blue-500 to-sky-400",
        avatarUrl: null,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },

    // ── Accountants ───────────────────────────────────────────
    {
        id: "31",
        name: "Beatrice Nkomo",
        email: "beatrice.nkomo@example.com",
        role: "accountant",
        title: "Bookkeeper & Accountant",
        hourlyRate: "38.00",
        skills: ["QuickBooks", "Xero", "Payroll", "Tax Preparation"],
        status: "available",
        rating: "4.9",
        projectsCompleted: 57,
        bio: "CPA with 9 years managing books for SMEs and startups. Expert in cloud accounting tools and financial reporting for US and international clients.",
        gradient: "from-emerald-500 to-teal-400",
        avatarUrl: null,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "32",
        name: "Henrik Larsen",
        email: "henrik.larsen@example.com",
        role: "accountant",
        title: "Financial Controller",
        hourlyRate: "65.00",
        skills: ["GAAP", "Financial Modeling", "NetSuite", "FP&A"],
        status: "busy",
        rating: "4.8",
        projectsCompleted: 29,
        bio: "Fractional CFO and controller who prepares scaling companies for fundraising and audits. Has supported 3 startups through Series A and B rounds.",
        gradient: "from-indigo-500 to-blue-400",
        avatarUrl: null,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },

    // ── Video Editors ─────────────────────────────────────────
    {
        id: "33",
        name: "Luna Espinoza",
        email: "luna.espinoza@example.com",
        role: "video_editor",
        title: "Video Editor",
        hourlyRate: "40.00",
        skills: ["Premiere Pro", "After Effects", "Color Grading", "YouTube"],
        status: "available",
        rating: "4.9",
        projectsCompleted: 73,
        bio: "Fast-turnaround video editor specializing in YouTube content and social media shorts. Edited videos that have collectively amassed 50M+ views.",
        gradient: "from-pink-500 to-rose-400",
        avatarUrl: null,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "34",
        name: "Andrei Popescu",
        email: "andrei.popescu@example.com",
        role: "video_editor",
        title: "Motion Graphics Designer",
        hourlyRate: "52.00",
        skills: ["After Effects", "Cinema 4D", "DaVinci Resolve", "Lottie"],
        status: "available",
        rating: "4.8",
        projectsCompleted: 48,
        bio: "Motion designer who brings brands to life through animation. Created broadcast-quality motion packages for clients in Europe, US, and Southeast Asia.",
        gradient: "from-orange-500 to-red-400",
        avatarUrl: null,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },

    // ── SEO Specialists ───────────────────────────────────────
    {
        id: "35",
        name: "Nadia Okonkwo",
        email: "nadia.okonkwo@example.com",
        role: "seo_specialist",
        title: "SEO Specialist",
        hourlyRate: "45.00",
        skills: ["Ahrefs", "Semrush", "On-Page SEO", "Link Building"],
        status: "available",
        rating: "4.9",
        projectsCompleted: 39,
        bio: "SEO strategist who drives compounding organic growth. Took 3 SaaS blogs from 0 to 100K monthly visitors through systematic content and technical SEO.",
        gradient: "from-cyan-500 to-emerald-400",
        avatarUrl: null,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: "36",
        name: "Mateus Oliveira",
        email: "mateus.oliveira@example.com",
        role: "seo_specialist",
        title: "Technical SEO Specialist",
        hourlyRate: "50.00",
        skills: ["Core Web Vitals", "Schema Markup", "Screaming Frog", "Google Search Console"],
        status: "busy",
        rating: "4.7",
        projectsCompleted: 31,
        bio: "Technical SEO expert who fixes the infrastructure issues that hold sites back. Specializes in crawlability, indexation, and Core Web Vitals optimization.",
        gradient: "from-teal-500 to-sky-400",
        avatarUrl: null,
        isVisible: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
]