export type Talent = {
    id: string
    name: string
    role:
    | "developer"
    | "va"
    | "project_manager"
    | "designer"
    | "ui_ux"
    | "data_analyst"
    | "content_writer"
    | "marketing"
    | "customer_support"
    | "accountant"
    | "video_editor"
    | "seo_specialist"
    | "qa"
    | "devops"
    title: string
    rate: number
    skills: string[]
    status: "available" | "busy" | "resigned" | "unavailable"
    rating: number
    projects: number
    bio: string
    gradient: string
    companyId?: number
    companyName?: string
    isResigned?: boolean
}

export const talents: Talent[] = [

    // ── Developers ────────────────────────────────────────────
    {
        id: "1",
        name: "Alex Rivera",
        role: "developer",
        title: "Full-Stack Developer",
        rate: 45,
        skills: ["React", "Node.js", "PostgreSQL", "TypeScript"],
        status: "available",
        rating: 4.9,
        projects: 42,
        bio: "8 years building scalable web applications for startups and enterprises. Specialist in React ecosystems and cloud-native architecture.",
        gradient: "from-blue-500 to-cyan-400",
    },
    {
        id: "4",
        name: "Priya Mehta",
        role: "developer",
        title: "Frontend Developer",
        rate: 40,
        skills: ["Next.js", "Tailwind", "TypeScript", "Figma"],
        status: "available",
        rating: 4.9,
        projects: 56,
        bio: "Pixel-perfect frontend developer who bridges design and engineering. Passionate about performance, accessibility, and great UX.",
        gradient: "from-emerald-500 to-teal-400",
    },
    {
        id: "5",
        name: "Carlos Mendez",
        role: "developer",
        title: "Backend Developer",
        rate: 50,
        skills: ["Python", "Django", "AWS", "Docker"],
        status: "available",
        rating: 4.7,
        projects: 38,
        bio: "Backend specialist focused on building robust APIs and cloud infrastructure. Experienced with high-traffic systems and microservices.",
        gradient: "from-orange-500 to-amber-400",
    },
    {
        id: "9",
        name: "Liam Torres",
        role: "developer",
        title: "Blockchain Developer",
        rate: 75,
        skills: ["Solidity", "Ethereum", "Web3.js", "Hardhat"],
        status: "available",
        rating: 4.9,
        projects: 19,
        bio: "Smart contract engineer with deep expertise in DeFi protocols and NFT platforms. Audited 10+ production contracts with zero critical vulnerabilities.",
        gradient: "from-indigo-500 to-violet-400",
    },
    {
        id: "10",
        name: "Yuna Park",
        role: "developer",
        title: "DevOps Engineer",
        rate: 65,
        skills: ["Kubernetes", "Terraform", "CI/CD", "GCP"],
        status: "available",
        rating: 4.8,
        projects: 33,
        bio: "Infrastructure engineer who lives in the terminal. Specializes in zero-downtime deployments, cost optimization, and building DevOps culture from scratch.",
        gradient: "from-cyan-500 to-sky-400",
    },
    {
        id: "11",
        name: "Marco Reyes",
        role: "developer",
        title: "AI / ML Engineer",
        rate: 80,
        skills: ["Python", "PyTorch", "LangChain", "OpenAI API"],
        status: "available",
        rating: 5.0,
        projects: 17,
        bio: "Machine learning engineer focused on LLM integration and production AI pipelines. Built RAG systems and fine-tuned models for 3 SaaS products.",
        gradient: "from-amber-500 to-orange-400",
    },
    {
        id: "8",
        name: "Aisha Patel",
        role: "developer",
        title: "Mobile Developer",
        rate: 48,
        skills: ["React Native", "iOS", "Android", "Expo"],
        status: "busy",
        rating: 4.8,
        projects: 29,
        bio: "Mobile-first developer with 6 years shipping apps on both iOS and Android. Expert in React Native and cross-platform performance.",
        gradient: "from-lime-500 to-green-400",
    },

    // ── Virtual Assistants ────────────────────────────────────
    {
        id: "2",
        name: "Maria Santos",
        role: "va",
        title: "Virtual Assistant",
        rate: 20,
        skills: ["Admin", "CRM", "Support", "Scheduling"],
        status: "unavailable",
        rating: 5.0,
        projects: 78,
        bio: "Detail-oriented VA with 5 years of executive support experience. Expert in automating workflows and managing high-volume inboxes.",
        gradient: "from-rose-500 to-pink-400",
        isResigned: true,
    },
    {
        id: "6",
        name: "Sophie Chen",
        role: "va",
        title: "Executive Assistant",
        rate: 25,
        skills: ["Notion", "Slack", "Research", "Social Media"],
        status: "available",
        rating: 4.9,
        projects: 63,
        bio: "Proactive EA with a background in operations. Highly organized, discreet, and experienced working with C-suite executives.",
        gradient: "from-fuchsia-500 to-pink-400",
    },
    {
        id: "12",
        name: "Fatima Reyes",
        role: "va",
        title: "E-commerce VA",
        rate: 22,
        skills: ["Shopify", "Amazon FBA", "Canva", "Customer Support"],
        status: "available",
        rating: 4.9,
        projects: 51,
        bio: "E-commerce specialist managing product listings, order fulfillment, and customer service for 7-figure Shopify and Amazon stores.",
        gradient: "from-rose-500 to-red-400",
    },
    {
        id: "13",
        name: "Grace Villanueva",
        role: "va",
        title: "Social Media Manager",
        rate: 28,
        skills: ["Instagram", "LinkedIn", "Content Planning", "Analytics"],
        status: "available",
        rating: 4.8,
        projects: 44,
        bio: "Social media strategist who turns brand voices into engaged communities. Managed accounts growing from 0 to 50K followers across multiple industries.",
        gradient: "from-pink-500 to-fuchsia-400",
    },

    // ── Project Managers ──────────────────────────────────────
    {
        id: "3",
        name: "James Kwon",
        role: "project_manager",
        title: "Project Manager",
        rate: 55,
        skills: ["Agile", "Scrum", "Jira", "Risk Management"],
        status: "busy",
        rating: 4.8,
        projects: 31,
        bio: "PMP-certified PM with a track record of delivering complex projects on time. Experienced in managing distributed teams across time zones.",
        gradient: "from-violet-500 to-purple-400",
    },
    {
        id: "7",
        name: "Daniel Osei",
        role: "project_manager",
        title: "Scrum Master",
        rate: 60,
        skills: ["Scrum", "Kanban", "Confluence", "Leadership"],
        status: "available",
        rating: 5.0,
        projects: 24,
        bio: "Certified Scrum Master who coaches teams to peak performance. Focused on removing blockers and building high-trust team cultures.",
        gradient: "from-sky-500 to-blue-400",
    },
    {
        id: "14",
        name: "Nathan Cruz",
        role: "project_manager",
        title: "Technical Program Manager",
        rate: 70,
        skills: ["Roadmapping", "Stakeholder Management", "OKRs", "Linear"],
        status: "busy",
        rating: 4.9,
        projects: 22,
        bio: "TPM with an engineering background who bridges product and engineering seamlessly. Experienced running programs across 4 time zones with 30+ person teams.",
        gradient: "from-violet-500 to-indigo-400",
    },

    // ── Designers ─────────────────────────────────────────────
    {
        id: "15",
        name: "Camille Fontaine",
        role: "designer",
        title: "Graphic Designer",
        rate: 45,
        skills: ["Photoshop", "Illustrator", "InDesign", "Branding"],
        status: "available",
        rating: 5.0,
        projects: 47,
        bio: "Versatile graphic designer with 8 years of experience in print and digital. Has shaped the visual identity of 20+ brands across various industries.",
        gradient: "from-fuchsia-500 to-rose-400",
    },
    {
        id: "16",
        name: "Rafael Domingo",
        role: "designer",
        title: "Brand & Motion Designer",
        rate: 50,
        skills: ["After Effects", "Illustrator", "Lottie", "Branding"],
        status: "available",
        rating: 4.8,
        projects: 38,
        bio: "Visual storyteller specializing in brand identity and motion graphics. Has shaped the visual identity of 20+ companies from seed to Series B.",
        gradient: "from-orange-500 to-yellow-400",
    },

    // ── UI/UX Designers ───────────────────────────────────────
    {
        id: "21",
        name: "Hana Kimura",
        role: "ui_ux",
        title: "UI/UX Designer",
        rate: 55,
        skills: ["Figma", "User Research", "Prototyping", "Design Systems"],
        status: "available",
        rating: 5.0,
        projects: 41,
        bio: "Product designer with a background in cognitive psychology. Creates interfaces that feel intuitive on first use — without a tutorial in sight.",
        gradient: "from-violet-500 to-fuchsia-400",
    },
    {
        id: "22",
        name: "Diego Morales",
        role: "ui_ux",
        title: "Product Designer",
        rate: 58,
        skills: ["Figma", "Framer", "Usability Testing", "Wireframing"],
        status: "busy",
        rating: 4.8,
        projects: 34,
        bio: "End-to-end product designer who owns projects from user research through pixel-perfect handoff. Deeply empathetic and data-informed in every design decision.",
        gradient: "from-blue-500 to-violet-400",
    },

    // ── Data Analysts ─────────────────────────────────────────
    {
        id: "23",
        name: "Selin Aydın",
        role: "data_analyst",
        title: "Data Analyst",
        rate: 52,
        skills: ["Python", "SQL", "Tableau", "Power BI"],
        status: "available",
        rating: 4.9,
        projects: 28,
        bio: "Analytical thinker who transforms raw data into clear business insights. Built dashboards tracking $50M+ in revenue across 3 enterprise clients.",
        gradient: "from-teal-500 to-cyan-400",
    },
    {
        id: "24",
        name: "Omar Farouk",
        role: "data_analyst",
        title: "Business Intelligence Analyst",
        rate: 58,
        skills: ["dbt", "Looker", "BigQuery", "Excel"],
        status: "available",
        rating: 4.7,
        projects: 22,
        bio: "BI specialist who builds the data infrastructure that lets teams make faster decisions. Experienced in e-commerce, fintech, and SaaS verticals.",
        gradient: "from-amber-500 to-yellow-400",
    },

    // ── Content Writers ───────────────────────────────────────
    {
        id: "25",
        name: "Isla MacPherson",
        role: "content_writer",
        title: "Content Writer",
        rate: 35,
        skills: ["Copywriting", "SEO Writing", "Blog Posts", "Email Campaigns"],
        status: "available",
        rating: 4.9,
        projects: 89,
        bio: "Versatile writer who crafts content that ranks and converts. Produced 500+ articles across SaaS, health, and finance niches over 6 years.",
        gradient: "from-lime-500 to-emerald-400",
    },
    {
        id: "26",
        name: "Tomás Herrera",
        role: "content_writer",
        title: "Technical Writer",
        rate: 40,
        skills: ["API Docs", "Developer Guides", "Markdown", "Confluence"],
        status: "available",
        rating: 4.8,
        projects: 53,
        bio: "Technical writer who makes complex systems understandable. Documented 15+ APIs and built doc sites that reduced support tickets by 40%.",
        gradient: "from-sky-500 to-blue-400",
    },

    // ── Marketing ─────────────────────────────────────────────
    {
        id: "27",
        name: "Zoe Andersen",
        role: "marketing",
        title: "Digital Marketing Strategist",
        rate: 55,
        skills: ["Google Ads", "Meta Ads", "HubSpot", "Growth Hacking"],
        status: "available",
        rating: 4.9,
        projects: 36,
        bio: "Performance marketer obsessed with ROAS and LTV. Managed $2M+ in ad spend and built growth engines for B2B SaaS companies.",
        gradient: "from-rose-500 to-orange-400",
    },
    {
        id: "28",
        name: "Jin-ho Bae",
        role: "marketing",
        title: "Email Marketing Specialist",
        rate: 42,
        skills: ["Klaviyo", "Mailchimp", "A/B Testing", "Segmentation"],
        status: "busy",
        rating: 4.7,
        projects: 44,
        bio: "Email specialist who turns lists into revenue. Achieved consistent 35%+ open rates and built automated flows generating 6-figures in monthly recurring revenue.",
        gradient: "from-fuchsia-500 to-violet-400",
    },

    // ── Customer Support ──────────────────────────────────────
    {
        id: "29",
        name: "Amara Diallo",
        role: "customer_support",
        title: "Customer Support Specialist",
        rate: 22,
        skills: ["Zendesk", "Intercom", "Live Chat", "CRM"],
        status: "available",
        rating: 5.0,
        projects: 112,
        bio: "Empathetic support specialist with a 98% CSAT score across 5 years. Specializes in turning frustrated customers into loyal brand advocates.",
        gradient: "from-green-500 to-teal-400",
    },
    {
        id: "30",
        name: "Riku Tanaka",
        role: "customer_support",
        title: "Support Team Lead",
        rate: 32,
        skills: ["Team Leadership", "Escalation Management", "Freshdesk", "SLA"],
        status: "available",
        rating: 4.8,
        projects: 67,
        bio: "Support lead who builds and mentors high-performing teams. Reduced average resolution time by 45% at his last two companies through process redesign.",
        gradient: "from-blue-500 to-sky-400",
    },

    // ── Accountants ───────────────────────────────────────────
    {
        id: "31",
        name: "Beatrice Nkomo",
        role: "accountant",
        title: "Bookkeeper & Accountant",
        rate: 38,
        skills: ["QuickBooks", "Xero", "Payroll", "Tax Preparation"],
        status: "available",
        rating: 4.9,
        projects: 57,
        bio: "CPA with 9 years managing books for SMEs and startups. Expert in cloud accounting tools and financial reporting for US and international clients.",
        gradient: "from-emerald-500 to-teal-400",
    },
    {
        id: "32",
        name: "Henrik Larsen",
        role: "accountant",
        title: "Financial Controller",
        rate: 65,
        skills: ["GAAP", "Financial Modeling", "NetSuite", "FP&A"],
        status: "busy",
        rating: 4.8,
        projects: 29,
        bio: "Fractional CFO and controller who prepares scaling companies for fundraising and audits. Has supported 3 startups through Series A and B rounds.",
        gradient: "from-indigo-500 to-blue-400",
    },

    // ── Video Editors ─────────────────────────────────────────
    {
        id: "33",
        name: "Luna Espinoza",
        role: "video_editor",
        title: "Video Editor",
        rate: 40,
        skills: ["Premiere Pro", "After Effects", "Color Grading", "YouTube"],
        status: "available",
        rating: 4.9,
        projects: 73,
        bio: "Fast-turnaround video editor specializing in YouTube content and social media shorts. Edited videos that have collectively amassed 50M+ views.",
        gradient: "from-pink-500 to-rose-400",
    },
    {
        id: "34",
        name: "Andrei Popescu",
        role: "video_editor",
        title: "Motion Graphics Designer",
        rate: 52,
        skills: ["After Effects", "Cinema 4D", "DaVinci Resolve", "Lottie"],
        status: "available",
        rating: 4.8,
        projects: 48,
        bio: "Motion designer who brings brands to life through animation. Created broadcast-quality motion packages for clients in Europe, US, and Southeast Asia.",
        gradient: "from-orange-500 to-red-400",
    },

    // ── SEO Specialists ───────────────────────────────────────
    {
        id: "35",
        name: "Nadia Okonkwo",
        role: "seo_specialist",
        title: "SEO Specialist",
        rate: 45,
        skills: ["Ahrefs", "Semrush", "On-Page SEO", "Link Building"],
        status: "available",
        rating: 4.9,
        projects: 39,
        bio: "SEO strategist who drives compounding organic growth. Took 3 SaaS blogs from 0 to 100K monthly visitors through systematic content and technical SEO.",
        gradient: "from-cyan-500 to-emerald-400",
    },
    {
        id: "36",
        name: "Mateus Oliveira",
        role: "seo_specialist",
        title: "Technical SEO Specialist",
        rate: 50,
        skills: ["Core Web Vitals", "Schema Markup", "Screaming Frog", "Google Search Console"],
        status: "busy",
        rating: 4.7,
        projects: 31,
        bio: "Technical SEO expert who fixes the infrastructure issues that hold sites back. Specializes in crawlability, indexation, and Core Web Vitals optimization.",
        gradient: "from-teal-500 to-sky-400",
    },

    // ── QA Engineers ──────────────────────────────────────────
    {
        id: "17",
        name: "Elena Vasquez",
        role: "qa",
        title: "QA Engineer",
        rate: 42,
        skills: ["Playwright", "Cypress", "API Testing", "Test Planning"],
        status: "available",
        rating: 4.9,
        projects: 35,
        bio: "Automation-first QA engineer who builds test suites that catch bugs before users do. Reduced production incidents by 70% at her last two engagements.",
        gradient: "from-teal-500 to-emerald-400",
    },
    {
        id: "18",
        name: "Kevin Huang",
        role: "qa",
        title: "QA Lead",
        rate: 52,
        skills: ["Test Strategy", "Selenium", "Load Testing", "JIRA"],
        status: "available",
        rating: 4.7,
        projects: 27,
        bio: "QA lead who builds quality processes, not just test cases. Experienced setting up QA from scratch at 3 fast-growing startups.",
        gradient: "from-sky-500 to-cyan-400",
    },

    // ── DevOps / Infra ────────────────────────────────────────
    {
        id: "19",
        name: "Isaac Mensah",
        role: "devops",
        title: "Cloud Infrastructure Engineer",
        rate: 68,
        skills: ["AWS", "Docker", "Ansible", "Monitoring"],
        status: "available",
        rating: 4.8,
        projects: 30,
        bio: "Cloud engineer with 7 years designing resilient, cost-efficient infrastructure on AWS. Comfortable owning the full stack from VPC to application layer.",
        gradient: "from-blue-500 to-indigo-400",
    },
    {
        id: "20",
        name: "Bianca Lim",
        role: "devops",
        title: "Site Reliability Engineer",
        rate: 72,
        skills: ["SRE", "Prometheus", "PagerDuty", "Go"],
        status: "busy",
        rating: 4.9,
        projects: 21,
        bio: "SRE focused on reliability, observability, and incident response. Helped scale a fintech platform to 99.99% uptime handling 2M+ daily transactions.",
        gradient: "from-emerald-500 to-green-400",
    },
]