
export { clientService, ClientService } from "./client.service"
export { talentService, TalentService } from "./talent.service"
export { inquiryService, InquiryService } from "./inquiry.service"
export { activityService, ActivityService } from "./activity.service"
export { placementService, PlacementService } from "./placement.service"
export { projectService, ProjectService } from "./project.service"
export { serviceService, ServiceService } from "./service.service"
export { notificationService, NotificationService } from "./notification.service"
export { settingsService, SettingsService } from "./settings.service"
export { uploadService, UploadService } from "./upload.service"
export { productService, ProductService } from "./product.service"
export { announcementService, AnnouncementService } from "./announcement.service"
export { contractService, ContractService } from "./contract.service"
export { BaseService } from "./base.service"
