import { CSSProperties } from "react";

export const joinConfirmationStyles: Record<string, CSSProperties> = {
    body: {
        backgroundColor: "#f4f4f5",
        fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
        margin: 0,
        padding: "40px 0",
    },
    container: {
        maxWidth: "560px",
        margin: "0 auto",
        padding: "0 20px",
    },
    header: {
        backgroundColor: "#ffffff",
        border: "1px solid #e4e4e7",
        borderRadius: "16px",
        padding: "32px",
        marginBottom: "16px",
        textAlign: "center",
    },
    headerLabel: {
        color: "#d97706",
        fontSize: "11px",
        fontWeight: "700",
        letterSpacing: "2px",
        margin: "0 0 12px 0",
    },
    headerTitle: {
        color: "#09090b",
        fontSize: "26px",
        fontWeight: "700",
        margin: "0 0 8px 0",
        lineHeight: "1.2",
    },
    headerSub: {
        color: "#71717a",
        fontSize: "14px",
        margin: "0",
    },
    card: {
        backgroundColor: "#ffffff",
        border: "1px solid #e4e4e7",
        borderRadius: "16px",
        padding: "24px 28px",
        marginBottom: "16px",
    },
    sectionLabel: {
        color: "#a1a1aa",
        fontSize: "10px",
        fontWeight: "700",
        letterSpacing: "2px",
        margin: "0 0 12px 0",
    },
    divider: {
        borderColor: "#e4e4e7",
        margin: "0 0 20px 0",
    },
    bodyText: {
        color: "#3f3f46",
        fontSize: "13px",
        lineHeight: "1.6",
        margin: "0 0 20px 0",
    },
    accent: {
        color: "#d97706",
        fontWeight: "600",
        display: "inline",
    },
    stepItem: {
        display: "flex",
        alignItems: "flex-start",
        gap: "12px",
        marginBottom: "16px",
    },
    stepBadge: {
        width: "24px",
        height: "24px",
        borderRadius: "999px",
        backgroundColor: "#fef3c7",
        border: "1px solid #fde68a",
        color: "#92400e",
        fontSize: "11px",
        fontWeight: "700",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        flexShrink: 0,
    },
    stepContent: {
        flex: 1,
    },
    stepTitle: {
        color: "#09090b",
        fontSize: "13px",
        fontWeight: "600",
        margin: "0 0 2px 0",
    },
    stepDesc: {
        color: "#71717a",
        fontSize: "12px",
        lineHeight: "1.5",
        margin: "0",
    },
    ctaSection: {
        backgroundColor: "#fffbeb",
        border: "1px solid #fde68a",
        borderRadius: "12px",
        padding: "20px 24px",
        marginBottom: "16px",
    },
    ctaTitle: {
        color: "#92400e",
        fontSize: "13px",
        fontWeight: "700",
        margin: "0 0 6px 0",
    },
    ctaText: {
        color: "#92400e",
        fontSize: "13px",
        lineHeight: "1.6",
        margin: "0",
    },
    footer: {
        padding: "0",
        marginBottom: "40px",
    },
    footerText: {
        color: "#a1a1aa",
        fontSize: "11px",
        lineHeight: "1.6",
        textAlign: "center",
        margin: "12px 0 0 0",
    },
}