import type { CSSProperties } from "react"

export const joinEmailStyles: Record<string, CSSProperties> = {
    body: {
        backgroundColor: "#f4f4f5",
        fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
        margin: 0,
        padding: "40px 0",
    },
    container: {
        maxWidth: "600px",
        margin: "0 auto",
        padding: "0 20px",
    },
    header: {
        backgroundColor: "#ffffff",
        border: "1px solid #e4e4e7",
        borderRadius: "16px",
        padding: "32px",
        marginBottom: "16px",
        textAlign: "center",
    },
    headerLabel: {
        color: "#d97706",
        fontSize: "11px",
        fontWeight: "700",
        letterSpacing: "2px",
        margin: "0 0 12px 0",
    },
    headerTitle: {
        color: "#09090b",
        fontSize: "24px",
        fontWeight: "700",
        margin: "0 0 8px 0",
        lineHeight: "1.2",
    },
    headerSub: {
        color: "#71717a",
        fontSize: "14px",
        margin: "0",
    },
    roleBadge: {
        display: "inline-block",
        backgroundColor: "#fef3c7",
        border: "1px solid #fde68a",
        borderRadius: "999px",
        padding: "4px 14px",
        color: "#92400e",
        fontSize: "12px",
        fontWeight: "700",
        marginTop: "12px",
    },
    card: {
        backgroundColor: "#ffffff",
        border: "1px solid #e4e4e7",
        borderRadius: "16px",
        padding: "24px 28px",
        marginBottom: "16px",
    },
    sectionLabel: {
        color: "#a1a1aa",
        fontSize: "10px",
        fontWeight: "700",
        letterSpacing: "2px",
        margin: "0 0 12px 0",
    },
    divider: {
        borderColor: "#e4e4e7",
        margin: "0 0 20px 0",
    },
    labelCol: {
        width: "130px",
    },
    label: {
        color: "#71717a",
        fontSize: "12px",
        margin: "0",
    },
    value: {
        color: "#18181b",
        fontSize: "13px",
        fontWeight: "500",
        margin: "0",
    },
    valueAccent: {
        color: "#d97706",
        fontSize: "13px",
        fontWeight: "500",
        margin: "0",
    },
    skillsWrap: {
        display: "flex",
        flexWrap: "wrap",
        gap: "6px",
        marginTop: "4px",
    },
    skillBadge: {
        display: "inline-block",
        backgroundColor: "#f4f4f5",
        border: "1px solid #e4e4e7",
        borderRadius: "8px",
        padding: "3px 10px",
        color: "#3f3f46",
        fontSize: "12px",
        fontWeight: "500",
    },
    experienceItem: {
        borderLeft: "3px solid #fde68a",
        paddingLeft: "14px",
        marginBottom: "16px",
    },
    experienceRole: {
        color: "#09090b",
        fontSize: "13px",
        fontWeight: "600",
        margin: "0 0 2px 0",
    },
    experienceDuration: {
        color: "#a1a1aa",
        fontSize: "11px",
        margin: "0 0 6px 0",
    },
    experienceDesc: {
        color: "#52525b",
        fontSize: "12px",
        lineHeight: "1.6",
        margin: "0",
    },
    linkItem: {
        display: "inline-block",
        color: "#d97706",
        fontSize: "13px",
        fontWeight: "500",
        textDecoration: "underline",
        margin: "0",
    },
    certItem: {
        backgroundColor: "#f0fdf4",
        border: "1px solid #bbf7d0",
        borderRadius: "8px",
        padding: "6px 12px",
        color: "#166534",
        fontSize: "12px",
        fontWeight: "500",
        marginBottom: "6px",
    },
    bio: {
        color: "#3f3f46",
        fontSize: "13px",
        lineHeight: "1.7",
        margin: "0",
        whiteSpace: "pre-wrap",
    },
    ctaSection: {
        backgroundColor: "#fffbeb",
        border: "1px solid #fde68a",
        borderRadius: "12px",
        padding: "16px 20px",
        marginBottom: "16px",
        textAlign: "center",
    },
    ctaText: {
        color: "#92400e",
        fontSize: "13px",
        fontWeight: "500",
        margin: "0",
    },
    footer: {
        padding: "0",
        marginBottom: "40px",
    },
    footerText: {
        color: "#a1a1aa",
        fontSize: "11px",
        lineHeight: "1.6",
        textAlign: "center",
        margin: "12px 0 0 0",
    },
}